---
title: 'STAT 422: HW #6'
author: 'Due: April 4, 2022, 11:59pm'
output: pdf_document
fontsize: 12 pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 5, fig.height = 4, out.width = "0.45\\linewidth", fig.align = "center")
```

# Problem 1
## Statement
Let $X_1,...,X_n$ be a random sample from the distribution with the following pdf: $$f(x;\theta) = \theta x^{\theta -1}I_{(0,1)}(x), \text{ where } \theta > 0$$

  a. Find a complete sufficient statistic for $\theta$  
  b. Using your answer in part (a), explain why $\displaystyle \prod_{i = 1}^n X_i$ is also a sufficient statistic for $\theta$. 
   
## Solution

a. Goal is to show that this is exponential family. 
So we want to write $f(x;\theta) = h(x) c(\theta) \exp\left(\sum_{j=1}^k t_j(x)w_j(\theta) \right)$.
\begin{align*}
f(x;\theta) &= \prod_{i=1}^n \theta x_i^{\theta -1} \\
&= \prod_{i=1}^n \theta \exp\left( (\theta -1) \ln(x_i) \right) \\
&= \theta^n \exp\left( \sum_{i=1}^n \ln(x_i)(\theta - 1) \right) \\
\end{align*}
where $h(x) = 1, c(\theta) = \theta^n, t(x) = \sum \ln(x_i), w(\theta) = (\theta -1)$.
Thus by the Exponential Family theorem: $\sum \ln(x_i)$ is a CSS.

b. We can see this via Factorization theorem in a (hand wavy way). We show sufficiency but not completeness. So for completeness, we need a one-to-one function that maps $\sum \ln(x_i)$ to $\prod x_i$.
We essentially did this in part a, we just now have to walk backwards. 
$e^x$ is one-to-one. So we take $\exp(\sum \ln(x_i)) = \prod \exp(\ln(x_i)) = \prod_{i=1}^n x_i$
As required :)






# Problem 2
## Statement

A real estate firm wants to estimate the rate of new houses sold in a week in Bozeman. Assume $X_1,...,X_n$ is a random sample of weekly house sales in Bozeman, where each $X_i$ is a Poisson random variable with mean $\mu$. The observed number of new houses sold per week for 5 randomly chosen weeks, were 2, 3, 3, 4, and 6. Find the best unbiased estimator (i.e., the UMVUE) of $\mu$ and its estimate. Show all work, and carefully explain why it is the UMVUE.    

## Solution

First, what is the pdf of Poisson? $p(y) = \frac{\lambda^y e^{-y}}{y!}$.
We want an UMVUE for $\lambda$. 
First we want to check if it is exponential family.

\begin{align*}
p(y; \lambda) &= \prod_{i=1}^n \frac{\lambda^{y_i} e^{-y_i}}{y_i!}\\
&= \prod_{i=1}^n \frac{1}{y_i!} \lambda^{y_i} e^{-y_i} \\
&= \prod_{i=1}^n \frac{1}{y_i!} \exp( y_i \ln(\lambda) - y_i )\\
&= \prod_{i=1}^n \frac{1}{y_i!} \exp( (\lambda - 1)y_i)\\
&= \left(\prod_{i=1}^n \frac{1}{y_i!}\right) \left( \exp( \sum_{i=1}^n(\lambda - 1)y_i) \right)\\
\end{align*}

where $h(x) = \prod_{i=1}^n \frac{1}{y_i!}, c(\theta) = 1, t(x) = \sum y_i, w(\theta) = (\lambda -1)$.
Thus by the Exponential Family theorem: $\sum y_i$ is a CSS.

Next we need $g(\sum y_i)$ such that $\mathbb{E}[g(\sum y_i)] = \lambda$.
Pick $g(\sum_{i=1}^n y_i) = 1/n \sum_{i=1}^n y_i$. 

\begin{align*}
\mathbb{E}[g(\sum y_i)] &= \mathbb{E}[1/n \sum_{i=1}^n y_i] \\
&= 1/n \sum_{i=1}^n \mathbb{E}[y_i] \\
&= 1/n \sum_{i=1}^n \lambda \\
&= \lambda
\end{align*}

As required,
where step three follows from the expected value of a poisson distribution.



  